cicd pipeline changes based on the latest version in git

diff --git a/bin/cfn/cicd-deploy b/bin/cfn/cicd-deploy
--- a/bin/cfn/cicd-deploy
+++ b/bin/cfn/cicd-deploy
@@ -1,8 +1,10 @@
 #! /usr/bin/env bash
-set -e # stop the execution of the script if it fails
+#set -e # stop the execution of the script if it fails
 
 CFN_PATH="$HOME/Developer/tutorials/awsBootcamp/aws-bootcamp-cruddur-2023/aws/cfn/cicd/template.yaml"
 CONFIG_PATH="$HOME/Developer/tutorials/awsBootcamp/aws-bootcamp-cruddur-2023/aws/cfn/cicd/config.toml"
+PACKAGED_PATH="$HOME/Developer/tutorials/awsBootcamp/aws-bootcamp-cruddur-2023/tmp/packaged-template.yaml"
+PARAMETERS=$(cfn-toml params v2 -t "$CONFIG_PATH")
 echo "$CFN_PATH"
 
 cfn-lint "$CFN_PATH"
